services:
  - type: web
    name: blockchain-based-evoting-system
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_FORCE_HTTPS
        value: "true"
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MPESA_ENVIRONMENT
        value: sandbox
      - key: MPESA_SIMULATE
        value: "true"
